### ISSUE TITLE
Autocomplete suggestions do not follow the field

### ISSUE THREAD

**Issue by jdanish** [netcreateorg/netcreate-itest#122]
Start typing into a field (e.g., search or more commonly edge target) and the autocomplete appears right below. Then scroll. It remains behind, often in an awkward position. Ideally it'd follow the field for more intuitive use. 

<img width="323" alt="Screenshot 2024-01-19 at 8 58 21 AM" src="https://github.com/netcreateorg/netcreate-itest/assets/5529898/645121ae-98d0-42f0-9b75-2cee0438135b">

**Comment by benloh** [comment]
Fixed with cc1e0f438ecc5e4f7433b3d988cf3de261977c4f
