### ISSUE TITLE
Filter summary still lists filtered items that were added and then removed

### ISSUE THREAD

**Issue by jdanish** [netcreateorg/netcreate-itest#124]
Click views, then click type, then unselect type, then select something else like male. The type is still listed in the filter summary bar though not impacting the filter. If you clear filters it goes away.

<img width="1053" alt="Screenshot 2024-01-19 at 2 34 49 PM" src="https://github.com/netcreateorg/netcreate-itest/assets/5529898/b1584b01-04c2-430d-bbda-24799ca8840d">

**Comment by benloh** [comment]
Fixed with fb4b0849635ccc2b6ff5f95508dae067ebc5a350
