### ISSUE TITLE
Focus filter doesn't update edges table if nodes table has focus

### ISSUE THREAD

**Issue by jdanish** [netcreateorg/netcreate-itest#126]
Click on nodes table to display it
Click on focus filter
Click on a node
Nodes table hides many nodes (correctly)
Click on edges (all still visible)
Click on the same node again (edges filter so you only see the visible / appropriate ones)

**Comment by benloh** [comment]
So the issue here is that the Edge Table does not re-run the focus filter when you switch to the Edge Table, but Node Table does not have that problem (e.g. you can have the Edge Table selected, select a focus, switch to Node Table, but the Node Table is properly filtered)

**Comment by jdanish** [comment]
Looks fixed now, by the way.
