### ISSUE TITLE
Add comment checkbox fields

### ISSUE THREAD

**Issue by jdanish** [netcreateorg/netcreate-itest#144]
Joshua writes: Thinking about how to get kids to provide more info in the comments - would it be hard to modify the template based system that you are setting up in net.create to also allow for check-box fields, and drop-down multiple choice fields as part of what goes in a comment? Like a student could pick "Evidence" then check "is missing" or "is incorrect" and then explain in a text box?

https://inquirium.slack.com/archives/C04DTUVARMM/p1709747825843339

**Comment by jdanish** [comment]
@benloh Note: for the new comment types (check-box, star, drop-down) it'd be awesome if they can eventually also be field types for the actual node properties. I figured I'd mention it in case it is easier to do some of the code only once.

**Comment by benloh** [comment]
> Note: for the new comment types (check-box, star, drop-down) it'd be awesome if they can eventually also be field types for the actual node properties. I figured I'd mention it in case it is easier to do some of the code only once.

We're not quite at the point of having a generic component that can handle this.  But perhaps with one or two levels of refactoring we can probably get there.  Partly it depends on how integrated it'll need to be to the rest of the app.

**Comment by benloh** [comment]
Implemented with #201
