### ISSUE TITLE
Add comment multiple choice fields

### ISSUE THREAD

**Issue by jdanish** [netcreateorg/netcreate-itest#145]
Joshua writes: Thinking about how to get kids to provide more info in the comments - would it be hard to modify the template based system that you are setting up in net.create to also allow for check-box fields, and drop-down multiple choice fields as part of what goes in a comment? Like a student could pick "Evidence" then check "is missing" or "is incorrect" and then explain in a text box?

https://inquirium.slack.com/archives/C04DTUVARMM/p1709747825843339

**Comment by benloh** [comment]
Implemented with #201
