### ISSUE TITLE
Expanding read / unread status and notification

### ISSUE THREAD

**Issue by jdanish** [netcreateorg/netcreate-itest#150]
From tinkering with the meme team, we realized that there is an added layer of complexity in that you might not open every model, or there might be too many read comments.

Proposal: 1) note the difference between unread and 2) unread replies.
A reply is defined as a response to a prior comment in both systems.
In meme, it is also defined as a response to my model.

We figure these can be different icons (number for unread, some symbol like an arrow over / next to it if a reply?).

We think that popups would be too distracting, so our pitch is to have a status indicator in both apps that shows unread comments and / or if they include replies anywhere in the system. In Net.Create top right near the logon token. In meme on the login screen where you see the list of models this might be displayed next to each model.

**Comment by benloh** [comment]
Implemented in #157.
