### ISSUE TITLE
Can't select Edge in EdgeTable

### ISSUE THREAD

**Issue by benloh** [netcreateorg/netcreate-itest#161]
In adding the ability to click on a comment unread status message in order to view an edge, I noticed that you can't actually select an edge from an Edge Table.  You can click "Edit" to edit the edge, and you can click a node label to open any source/target node, but you can't click anything to view it.

Do we want to add the ability to view an edge?  And if so, how should we do it?  Add a "View" button?  Add a "source->target" label (though that would eat up even more horizontal space and be repetitive)?

**Comment by jdanish** [comment]
It'd be cool. I think we can replace the current "edit" with view / edit and if we switch to icons it'll be similar space? (pencil and eye)  Then just switch the same for the node edit button? I don't think we need the source -> target to eat up space since it is already displayed. Would that fit?

**Comment by benloh** [comment]
Icons added.  See 17504be.
But this introduces a deeper problem: #162

**Comment by benloh** [comment]
@jdanish For parity we might want to consider adding a "View" button to the Node Table as well.  Currently to view a node you have to click on the name itself.  So that's a little different from the behavior of the Edge Table.  Should we add a "View" button?

**Comment by jdanish** [comment]
Yes please

**Comment by benloh** [comment]
Implemented with 6cf77698a0d9ffad0830a91c39ac2b3d05d07e7c
