### ISSUE TITLE
Edge Edit mode allows opening and selecting EdgeTable functions

### ISSUE THREAD

**Issue by benloh** [netcreateorg/netcreate-itest#162]
If the EdgeTable is open when you're editing an edge, then you can inadvertently open other nodes and edges, and even try to edit other edges.

This is not a problem with node editing, because node editing acts as a modal.

We can't use the modal approach with edges because we need to be able to select a node when setting edge sources and targets.

Possible solution: In Edge Table disable view and edit buttons and as well as source and target links to open nodes?

The proper solution probably requires some kind of general mode manager?

**Comment by jdanish** [comment]
> Possible solution: In Edge Table disable view and edit buttons and as well as source and target links to open nodes?

that works for me

**Comment by benloh** [comment]
Fixed by 4df4bdf4cb2618fc2d18c54d9ba24d37b55a099f

**Comment by benloh** [comment]
Addressed by #175
