### ISSUE TITLE
Try and optimize page load times

### ISSUE THREAD

**Issue by jdanish** [netcreateorg/netcreate-itest#166]

**Comment by jdanish** [comment]
@benloh I didn't see any easy way to order but I think we need to put a little time into this. This can wait until provenance and comments are working since ideally we'll use those with teachers to do co-design this summer. And if you need to push it for other things like auth and admin, AOK. But I wanted to make sure we planned some for it.

**Comment by benloh** [comment]
> page load

If you have a current project with bad load times that would help us figure out how how to optimize.  This is a pretty good time to do that.

> ordering

The key is to make sure you add the current iteration ("@4 Comment Design") for the project.  Then the "Current Iteration" view will have the lists of everything and that can be ordered: https://github.com/orgs/netcreateorg/projects/3/views/2

An easier way to do this is to just start from the project view and just use the "Add Item" -- that'll put you on the right iteration and let you order right away.  You can then convert the draft to an issue.  I just noticed that our link in the slack channel was using an expired iteration.  So I've updated it.  That's one of the annoying things about how github handles projects.

**Comment by jdanish** [comment]
It seems unrelated to the amount of data. For example, with only 3 nodes, this takes close to 5 seconds in chrome: http://198.211.109.198/graph/SeedsTest/#/edit/1-1-EK2

**Comment by jdanish** [comment]
<img width="224" alt="Screenshot 2024-04-19 at 12 14 04 PM" src="https://github.com/netcreateorg/netcreate-itest/assets/5529898/3ce2861b-2fbd-421e-9bcf-883a3156f4ed">

**Comment by benloh** [comment]
This is running on your laptop?
I'm seeing a TON of autoreload messages.  Do you have something that is causing the site to constant rebuild itself?

**Comment by jdanish** [comment]
That’s digital ocean and not that I know of?

**Comment by benloh** [comment]
![Image](https://github.com/netcreateorg/netcreate-itest/assets/1403057/ed47ab68-f8d3-492c-8fa0-e8c3280010fb)

DO is probably running in dev mode so it's detecting changes in the code and triggering recompiles.  Did this problem just start recently?

**Comment by benloh** [comment]
You might try `npm run classroom` instead, though I can't test that right now.

**Comment by jdanish** [comment]
I can try but isn’t it multiplex that does it?

**Comment by benloh** [comment]
Ah I didn't realize (but of course should have known) you were running multiplex too.  You could try running without multiplex to see if it has the same problem.  I know Sri has been looking into DO support as that has never been formally supported.

**Comment by benloh** [comment]
@jdanish did you run `npm run package` on https://github.com/netcreateorg/nc-multiplex step 3?  The autoreload is probably being caused by your building it using `npm run dev`?

I just did a local test and do not see the autoreloads.

Granted the nc-multiplex instructions are now a little confusing because of all the changes.

**Comment by jdanish** [comment]
OK, not a new issue, I just didn't report it since I assumed it was DO. running classroom is deprecated, so I was using ./nc.js but I now realize that uses dev. I switched the live server (same link) to package in step 3 and it a) seems much better, and b) doesn't seem to be causing as many errors in the console (none). So ... maybe not an issue at all! Let's revisit later if we have extra time, but otherwise mark this closed.

**Comment by benloh** [comment]
I'm updating the multiplex readme to address this.

**Comment by jdanish** [comment]
Thanks. I think this is my fault - when classroom no-longer worked, package seemed funny and the packaging isn't working currently so I assumed I'd use the one thing that does work (dev). I shoulda asked. Anyhow, no harm no foul. Thanks! 

Joshua

**Comment by benloh** [comment]
README updated: https://github.com/netcreateorg/nc-multiplex

**Comment by benloh** [comment]
Packaging may be buggy when trying to export it somewhere, but it still does what it's supposed to on DO in terms of building the files so that multiplex can run.

**Comment by jdanish** [comment]
Makes sense, thanks! Just explaining my logic, though all good and caught up now!
