### ISSUE TITLE
Comment indicators are on the wrong z-index and come in front of the toolbar when they should disappear

### ISSUE THREAD

**Issue by jdanish** [netcreateorg/netcreate-itest#167]
https://github.com/netcreateorg/netcreate-itest/assets/5529898/7df52f53-2201-45de-9e4a-72e7ebfb30c6

**Comment by benloh** [comment]
Good catch.

**Comment by benloh** [comment]
Fixed with a0250160200563ddba60793cdfe16a768416a37e
