### ISSUE TITLE
Z-index for comments sometimes puts comments behind Node-table drop down (cross-browser compatibility issue)

### ISSUE THREAD

**Issue by kalanicraig** [netcreateorg/netcreate-itest#170]
If you click on a node, choose edges tab, open an edge, and then click comments with the node-table display toggled to on, the comment display z-index puts the comment behind the node table in Safari. (Was testing in Safari; this seems not to be replicable in Chrome, but we'll have users using non-chrome browsers)
<img width="741" alt="Screenshot 2024-04-22 at 2 26 23 PM" src="https://github.com/netcreateorg/netcreate-itest/assets/9748020/9053c4c9-b9e5-4f64-8e5d-5e3d45ca773f">

**Comment by benloh** [comment]
@jdanish @kalanicraig What version of Safari are you using and what is your window size?  I'm not seeing it with version 17.4.1.

**Comment by benloh** [comment]
Already fixed.
