### ISSUE TITLE
Can we set a minimum size for the comment window?  

### ISSUE THREAD

**Issue by jdanish** [netcreateorg/netcreate-itest#172]
If the screen is small, the comment can become basically unreadable, so maybe having a minimum?

<img width="881" alt="Screenshot 2024-04-22 at 2 40 06 PM" src="https://github.com/netcreateorg/netcreate-itest/assets/5529898/60cca028-7fbe-4bd7-8342-2b348dbd2cd6">

**Comment by benloh** [comment]
Addressed with d4d28413faba2c1c92b49c6ba2289632e8193793
