### ISSUE TITLE
Standalone mode does not display comments

### ISSUE THREAD

**Issue by benloh** [netcreateorg/netcreate-itest#176]
In order to track read/unread status, we are currently require login to be able to view any comments.

But since standalone does not require login, comments are not currently displayed.

See https://github.com/netcreateorg/netcreate-2018/wiki/User-Guide

**Comment by benloh** [comment]
@jdanish Do we need to show comments in standalone mode?  Currently comments are ignored because we can't retrieve read/unread status without it.  If comments should always be visible, we probably want to introduce a view mode that does not show read/unread status.

**Comment by jdanish** [comment]
I think it'd be nice to include comments since we might put them in as a guide for viewers. I'm OK with it showing read / unread for the current session (so no change needed?).

**Comment by benloh** [comment]
OK that makes sense.
It does actually require some changes because read/unread status can only be determined after we get the login info

**Comment by jdanish** [comment]
How big a task is this?  I'm tempted to push it off if it feels like more than a few hours to make sure lots of more important things get done.

**Comment by benloh** [comment]
My guess is it's about two hours.  I believe it works with a logged out user, but the standalone stuff is older and we only just re-enabled that earlier today and have not really tested it yet.

**Comment by jdanish** [comment]
OK, then yeah it'd be cool to do now. Thanks!

**Comment by benloh** [comment]
Notes to self.  Look at:
* [X] Use `npm run package:debug` to test standalone mode live
* [X] trace `brunch-config` to see how standalone assets are being converted
* [X] look at `server-database.DB.WriteDbJSON` for jsonification
   * [X] How is the db being converted to json?
* [X] Look in `nc-logic` for `LOADASSETS`
   * [X] Need to trigger load for comments `nc-logic:239`
   * [X] Instead of comment-mgr.LOAD_COMMENT_DATACORE call, use an SetAppState('COMMENTDATA`)? -- emulate 187:m_PromiseLoadDB?
* [X] UNISYS is not active for standalone mode

**Comment by benloh** [comment]
Fixed with 773862b4fbe6c720eb8d0fd7640b9aff1c2dcc0b
