### ISSUE TITLE
In node view, collapsed edges should be color-coded to their type

### ISSUE THREAD

**Issue by jdanish** [netcreateorg/netcreate-itest#197]
I thought this was previously the case but it appears to have reverted to a generic gray. Can we re-implement? Thanks!

<img width="330" alt="PNG image" src="https://github.com/netcreateorg/netcreate-itest/assets/5529898/3018cdc1-f6c1-4dce-bb52-b3a68bec5ac3">

**Comment by benloh** [comment]
Fixed with #198.
