### ISSUE TITLE
z-index issue with comments being behind alert panel

### ISSUE THREAD

**Issue by jdanish** [netcreateorg/netcreate-itest#199]
Just noticed because we have a lot more comments now ...  not a huge deal, but if we can move comments above the alert that'd be good, otherwise it is confusing for them to appear behind.

<img width="755" alt="Screenshot 2024-05-03 at 2 30 07 PM" src="https://github.com/netcreateorg/netcreate-itest/assets/5529898/eae0b492-12ce-404a-9b2c-e4e18580a786">

**Comment by jdanish** [comment]
Note: not a huge issue, but good to address ...

**Comment by benloh** [comment]
Addressed with #200
