### ISSUE TITLE
Deleting comments may not re-show the close button

### ISSUE THREAD

**Issue by jdanish** [netcreateorg/netcreate-itest#209]
<img width="611" alt="Screenshot 2024-05-16 at 3 46 48 PM" src="https://github.com/netcreateorg/netcreate-itest/assets/5529898/d0530453-857c-4e12-9319-131d1199c4fa">

I believe the steps were:

1. Respond to comment
2. Go to original account in another window and delete original comment
3. Return here and delete bottom comment, this removes the entire thread
4. Close button should appear but does not

(reload works fine, but ... )

**Comment by benloh** [comment]
@jdanish I can't reproduce this.  Can you clarify the exact steps you're taking?

If the Close button is disabled, it probably means someone was in a comment edit mode.  But I'm not sure what sequence of events caused you to get stuck in edit mode?

**Comment by jdanish** [comment]
Sent video via slack, but it is:

1. User 1 makes comment 1
2. User 2 makes reply 1a
3. User 2 adds reply 1b (by replying to 1a)
4. User 1 deletes comment 1 (it is hidden, but 1a and1b remain)
5. User 2 deletes 1a (also hidden but not yet gone)
6. User 2 clicks to write a new comment (2) (accidentally?)
7. User 2 deletes comment 1b. This removes all of the prior comments in that thread as it should.
8. In the process, comment 2 was saved, but the close button remains faded

There may be a more direct path but that's how I found it ...

**Comment by jdanish** [comment]
Confirmed, more direct route:

1. Create comment 1
2. Create comment 2, but do not yet save
3. Delete comment 1. 
4. See that comment 1 is deleted, comment 2 is auto-saved, close is still faded.

So, I guess we just need to make sure the auto-save re-enables the close button if it saves due to navigating away by doing some other comment delete?

**Comment by benloh** [comment]
Thanks.  OK I think in this case, what I probably should be doing is disabling the "DELETE", "EDIT", and "REPLY" buttons on other comments while a comment is being edited.

**Comment by benloh** [comment]
@jdanish See if this fixes it.  It's in the `dev-bl/add-log-items` branch.

**Comment by jdanish** [comment]
Looks good! Thanks!
