### ISSUE TITLE
Have a way to scroll down to edges in the node info

### ISSUE THREAD

**Issue by jdanish** [netcreateorg/netcreate-itest#21]
Currently, if there are a lot of fields, the node summary doesn't display the edges above the fold. Having an edit or view edges link up top that auto-scrolls the panel will help remind users and get there quickly.

**Comment by benloh** [comment]
One idea here might be to enforce a fixed three row panel edit area: search, node, edges.

Pros
* All three are visible at the same time and can be expanded/minimized.  
* When editing a node, you can quickly get to edges, even though you can't see all of them
* When editing an edge, the name of the node is visible
* Search help text and "Add New Node" can be hidden when the Search panel is minimized.  It can be maximized on hover or click inside input field? But is Search really necessary to be visible when editing or viewing nodes and edges?

Cons
* Have to spend time managing the expansion/minimization

**Comment by jdanish** [comment]
I was thinking maybe a node would display label and comments and then have 2 tabs: properties and edges so you were hyper aware of where your focus was. Or maybe a property has an attribute that indicates whether it is always visible or on the properties tab but ... that'd let us keep the current footprint

**Comment by jdanish** [comment]
Kalani approves, though suggests "attributes" instead of properties.

**Comment by benloh** [comment]
So this becomes a very Node-oriented layout? 
When you edit an edge, are you doing so under the "Edges" tab?  Or does it open in a new window?
Whenever you want to view edges, you have to do an extra click.
What makes something an "Attribute"?  Why isn't "Type" an "Attribute"?

**Comment by jdanish** [comment]
It is.

Type is an attribute it's just one I was assuming we always want to see. Though it is confusing so moving it down might make sense. I assume you'd edit inside the edges tab so the context is always clear.

It is one extra click but in practice we were finding you had to scroll anyhow and thus it's a wash.

**Comment by jdanish** [comment]
After chatting with Kalani and looking at both Gephi and Kumu.io:

- While Name and Type are attributes, we agree they are useful minimal context. So, it's fine to just have them and think of the attributes tab as "other attributes" and just say that.
- While Gephi and Kumu treat edges as something totally separate (In Gephi you can't see edges easily on the nodes table, but have to go to the edge table), we both agree that is confusing and unnecessary - it makes it harder to grasp the data / organization / relationship.
- If your really want an edge focused view you have the table.
- I think making it clear that every node has attributes, edges and provenance is a unique feature of net.create that we'd want to play up, and that kids grok / will find useful. The abstraction levels in Gephi are nice for engineers, but just ... not as usable for non-engineers. IMHO.

**Comment by benloh** [comment]
This is critical enough that we might want to try a few quick prototypes to see how they feel.

So "Provenance" is also treated as a special field?  There are also fields that aren't currently shown, like creation and update date.  Maybe that is part of the "Provenance" tab?  I'm trying to think through how we might want to spec things in a new UI where you can arbitrarily define fields.  e.g. Nodes MUST have a "label";  Nodes must have meta data (creation date, etc), and these are always displayed under the "Provenance" tab;  Nodes have arbitrarily-defined custom fields that are displayed under "Attributes".

I must admit treating "Edges" as a second class citizen feels a little funny to me.

**Comment by benloh** [comment]
> While Gephi and Kumu treat edges as something totally separate (In Gephi you can't see edges easily on the nodes table, but have to go to the edge table), we both agree that is confusing and unnecessary - it makes it harder to grasp the data / organization / relationship.

So you're saying you do want edges to be subsumed under nodes?

**Comment by jdanish** [comment]
Sure - we can try it!

I agree that creation and update would go under provenance.

I guess I think of edges not so much as second-class-citizens but rather always contextualized within nodes. Right now they are already way down the screen.

So, yes, in the node editor that is currently on the left of the screen, edges would appear in that tab rather than just in the top-level panel. Otherwise no change - so clicking on an edge in the edge table would still open the node and then the edge within it as it currently does. The only difference would be going to the tab directly. 

An alternative would be to make it so that the attributes and edges might be collapsible but then you still need a reminder.

As a reminder, the report from my team is that with many attributes, students often forgot the edges were on there at all. So having the tab up top actually draws attention to them.

**Comment by jdanish** [comment]
Oh, and I'd say that a node must have a label, lest it is really confusing, and that everything other attribute can be specified as being on the top (always visible) or within the panel. Any provenance specific functionality would go in that tab, and edges would be obviously grouped.

I should also note that I imagine comments are a special thing, not an attribute, that would appear as an icon on the top and open a window as in meme. The Spring test uses an attribute field for comments, but that's a short-term solution.

**Comment by benloh** [comment]
Do we really want "Attributes", "Edges" and "Provenance" to be treated as three equal objects?  Should "Edges" be emphasized, e.g. with a color, or shape?  and "Provenance" de-emphasized, e.g. faded?

Would you ever want to view Provenance at the same time as Attributes?

**Comment by jdanish** [comment]
If we are just testing I’d say let’s just try it without emphasis. No I think provenance is always a tab.----(from my iPhone)Joshua Danishhttp://www.joshuadanish.comOn Jul 4, 2023, at 3:07 PM, benloh ***@***.***> wrote:﻿
Do we really want "Attributes", "Edges" and "Provenance" to be treated as three equal objects?  Should "Edges" be emphasized, e.g. with a color, or shape?  and "Provenance" de-emphasized, e.g. faded?
Would you ever want to view Provenance at the same time as Attributes?

**Comment by benloh** [comment]
Implemented #39.
