### ISSUE TITLE
Error on sort common col in node or edge table

### ISSUE THREAD

**Issue by jdanish** [netcreateorg/netcreate-itest#223]
Was previously working, but ... 

<img width="331" alt="Screenshot 2024-05-28 at 4 51 50 PM" src="https://github.com/netcreateorg/netcreate-itest/assets/5529898/9b91a6dd-1a61-4c61-b1bb-a12184bc0f42">

@benloh we are doing some stress testing tomorrow, and while we can ignore this, it'd be awesome if you have a quick fix. If not, no worries.

**Comment by benloh** [comment]
Should be a quick and easy fix.  Sorry about that.
