### ISSUE TITLE
View and edit buttons disappearing in current dev branch in tables (node and edge)

### ISSUE THREAD

**Issue by jdanish** [netcreateorg/netcreate-itest#225]
Just noticed. Click on node / edge table, view and edit buttons flash visible then disappear.

**Comment by jdanish** [comment]
This appears to have been created by some weird state we got into in the sense that it now works fine again. I'll see if I can reproduce, but if you have ideas let me know.

**Comment by benloh** [comment]
It's most likely related to someone locking and unlocking a comment, node, or edge.  This possibly includes network activity (e.g. someone else is editing).

There are a number of optimizations that we need to revisit.  We had to do a fair amount of locking/unlocking to make sure users can't inadvertently make certain changes while anything is being edited.  It probably would've been easier to establish some kind of edit modal approach, but you lose the ability to do stuff like select nodes as edge targets. 

On a slower Chromebook, for instance, you can see a flash of "This node is currently being edited by someone else, please try again later" as you save comments/nodes/edges.

**Comment by jdanish** [comment]
Looks like it might be due to template editing. Marking this closed since that's fine / correct.
