### ISSUE TITLE
Comment not closing after clicking around to other nodes

### ISSUE THREAD

**Issue by jdanish** [netcreateorg/netcreate-itest#238]
This is in interim-comment-template, and I have not checked if it was elsewhere.

Steps: 

1. Click a node.
2. Open comment
3. Click a different node (new comment appears in same spot)
4. Click close (comment won't close).
5. Return to original node.
6. Click close (it closes OK).

https://github.com/user-attachments/assets/2c604496-69a4-4e50-b576-a5c64feb41dd

**Comment by benloh** [comment]
Should be fixed now with #238.
