### ISSUE TITLE
Table view sorts when a new comment is added (shouldn't)

### ISSUE THREAD

**Issue by jdanish** [netcreateorg/netcreate-itest#250]
Steps:

1. Open nodes table
2. Sort by comments
3. Click on a comment icon
4. Comment dialogue appears
5. Click in the "Click to add comment" space
6. Notice that the nodes table reverts to default sort

This is somewhat confusing, but not a big deal / not urgent. However, it did seem worth noting in case the extra triggers are causing one of the other issues?

**Comment by benloh** [comment]
@jdanish Thanks for all the reports.  I assume this last batch of stuff is in the `resizable-tables` branch?

**Comment by jdanish** [comment]
Yes, I assumed you are trying to get that ready so it was the most useful focus. If I misunderstood please let me know.

**Comment by benloh** [comment]
This is probably going to be really hard to fix because we'd have to somehow:
1. disable the sort from happening temporarily
2. still update the comment icon count
3. re-enable the sort after detecting some other action.

Fix will be related to #249

**Comment by benloh** [comment]
Should be fixed with 56f5b9cc9c6e402c98fcff85bdb3fe7caa1e4672
