### ISSUE TITLE
Can't currently change edge target during initial edge creation

### ISSUE THREAD

**Issue by jdanish** [netcreateorg/netcreate-itest#254]
Steps:

1. Select a node
2. Select edges and new
3. Click to link the target
4. If you want to change it, you need to either cancel, or save and then return to edit. You should be able to select it and change it from here.

Not urgent, but found in recent testing so wanted on the list.

**Comment by benloh** [comment]
I believe this should be fixed with 01abeabfb2557fac144d01f4e260a82e95e03a7d
NOTE on branch `dev-bl/resizable-table`

**Comment by benloh** [comment]
@jdanish Please verify that this one is fixed.  In my testing it works, but I'm not 100% sure I am doing the same that you are.

**Comment by jdanish** [comment]
Confirmed fixed thanks!
