### ISSUE TITLE
Tooltips show fields that might not be part of the network

### ISSUE THREAD

**Issue by jdanish** [netcreateorg/netcreate-itest#255]
I think we'd either want to let the template choose, or maybe just trim down to label, type and degree?  Not urgent.

<img width="672" alt="Screenshot 2024-09-11 at 10 37 58 AM" src="https://github.com/user-attachments/assets/d166704d-3cfa-4c4f-8788-781f73668e71">

**Comment by benloh** [comment]
Should be fixed by #259.
