### ISSUE TITLE
Deleting of "required" fields from template leads network to not load

### ISSUE THREAD

**Issue by jdanish** [netcreateorg/netcreate-itest#256]
Steps to reproduce:

1. Load network and it displays
2. Edit template and remove a block such as:
`
[nodeDefs.info]
type = "number"
displayLabel = "Number"
exportLabel = "Info"
help = "Some number comparison"
includeInGraphTooltip = true
isProvenance = false
hidden = true
`
3. Reload network
4. Network does not load

I am not sure which are "required" fields.

**Comment by benloh** [comment]
Error
![screenshot_1710](https://github.com/user-attachments/assets/250e1427-4fee-42ec-9e62-0d4ca3aaf37f)

NOTES/LOG
* after removing the node definition, you quit and restart the server
* related to #255

**Comment by benloh** [comment]
Should be fixed by #259.
