### ISSUE TITLE
Edges table display needs to go behind header

### ISSUE THREAD

**Issue by jdanish** [netcreateorg/netcreate-itest#260]
<img width="1111" alt="Screenshot 2024-09-15 at 9 48 38 PM" src="https://github.com/user-attachments/assets/fff31dae-2613-465d-a04f-2ed5824ff03e">

**Comment by jdanish** [comment]
Can wait until later / not urgent

**Comment by benloh** [comment]
It's not clear why NCNodeTable does not have the same problem.  Setting `th` z-index seems to solve the problem.

**Comment by benloh** [comment]
Fixed with fa6f69c56fb221ee3b52ace35d116641d839872e
