### ISSUE TITLE
One of the edges appears red initially for some reason

### ISSUE THREAD

**Issue by jdanish** [netcreateorg/netcreate-itest#261]
One of the edges appears red, but then if I click "clear filters" it goes away. Not sure why it would be pre-filtered on load, though ...

<img width="1122" alt="Screenshot 2024-09-15 at 10 01 08 PM" src="https://github.com/user-attachments/assets/99dd19eb-8f50-4a62-aacd-e4e07aeb7004">

**Comment by jdanish** [comment]
Update, it appears to be more than 1. Not sure the pattern, nor what the red filter might mean even?

**Comment by benloh** [comment]
I believe this is a selection issue.  I was in the middle of implementing row highlighting based on selected nodes -- it's part of the plumbing I needed to restore for handling filtering via fading.

**Comment by benloh** [comment]
Fixed with 795f6769cc39d3729de366b63b4e51e3c0a1cccf
