### ISSUE TITLE
Edge table appears to insert a column for "Category" even if it is not in the template

### ISSUE THREAD

**Issue by jdanish** [netcreateorg/netcreate-itest#262]
To test, load a template that does not have "Category".  Look at edge table and it appears.

**Comment by benloh** [comment]
This was a backward compatibility fix added by Joshua by 8c9a229dc94b2f27e1d7ad01649d674f3625e280
> If category is missing, handle it gracefully for backwards compatibility. Eventually, we should remove this code, but it doesn't create a major slow-down.

Fixed by ac40193d69e9d03f29f2da6305e8c3ad7b2c779e
