### ISSUE TITLE
Font size is larger when running via multiplex then when running dev?

### ISSUE THREAD

**Issue by jdanish** [netcreateorg/netcreate-itest#264]
Is the font size set differently for a dev run?  This one is puzzling ...  

<img width="1725" alt="Screenshot 2024-09-15 at 10 51 18 PM" src="https://github.com/user-attachments/assets/b12b3c1c-d7ee-4f89-b791-c4c2cc9da264">

**Comment by jdanish** [comment]
Update, the better / smaller font appears to be present when running on my localhost, but not others. Not sure why that would be, but it is puzzling.

**Comment by benloh** [comment]
Stupid question: This is not a zoom issue?  If you open the other one in the same window do you have the same issue?

**Comment by jdanish** [comment]
Yeah, not a zoom issue. I am really puzzled. I looked at the style in google dev tools and it appears the same too. How big does it look to you?

**Comment by jdanish** [comment]
Nevermind, it does seem that window was zooming. Weird! Sorry, closing.
