### ISSUE TITLE
Error when changing templates that switches a field from a `markdown` to another type

### ISSUE THREAD

**Issue by benloh** [netcreateorg/netcreate-itest#311]
From Joshua
> For this, I opened a network, exported the template, changed one field label (website to website 2) and then imported and got a blank screen with this error. Once this is addressed I can try and test different attribute types (this one happened to be markdown).

[CRLT People.zip](https://github.com/user-attachments/files/18218633/CRLT.People.zip)

<img width="1696" alt="Screenshot 2024-12-21 at 7 50 19 AM" src="https://github.com/user-attachments/assets/df8f8322-1174-4ad7-9260-8ecb684e3c44" />

**Comment by benloh** [comment]
Error happens when a field, e.g. `notes` is switched from `markdown` to `string`.
Error is happening because the table is still trying to render the `markdown` field with the old column def, but the data has switched to `string`

**Comment by benloh** [comment]
Should be fixed with c0ad2541a84fe12ac999e5056d8f5d895d1fa89e

**Comment by benloh** [comment]
# To Replicate
1. Copy `CRLT_People.loki` and `CRLT_People.template.toml` to `/runtime`
2. Load CRLT_People.loki using `./nc.js --dataset=CRLT_People`
3. View the graph -- everything should look fine
4. Go to admin mode, and select More > Edit Template **and click "Choose File"**
5. Choose "_default.template.toml` and "Save Changes"
6. The graph colors should rever tto black
7. Select More > Edit Template > "CRLT_People.template.toml" and click "Save Changes"
8. The colors should revert.  There should be no errors in the console.

**Comment by benloh** [comment]
@jdanish I believe this is fixed now.  Please confirm.

**Comment by jdanish** [comment]
Do you mean click "new template". There is no dropdown to select the template?

**Comment by benloh** [comment]
> Do you mean click "new template". There is no dropdown to select the template?

Sorry: "4. Go to admin mode, and select More > Edit Template and click "Choose File""

**Comment by benloh** [comment]
To close this off...there were three problems.
1.  Exporting and re-importing templates were broken due to hidden fields not being exported. #296 #297.  Fixed with #308.
2. Exporting and re-importing were causing errors due to interim state updates as templates transitioned from one type to another #311 [# 284 comment](https://github.com/netcreateorg/netcreate-itest/issues/284#issuecomment-2558114447).  Fixed with #308 in c0ad2541a84fe12ac999e5056d8f5d895d1fa89e.
3. Importing a template with custom fields would cause JSON Editor to revert to predefined schemas, removing the custom fields.  The main comment in issue #284 is an example of the error.  Issue #115 is the proper description.
