### ISSUE TITLE
Duplicate node labels cannot be distinguished when selecting a source or target

### ISSUE THREAD

**Issue by benloh** [netcreateorg/netcreate-itest#38]
We're allowing the creation of multiple nodes with the same label.
However, when adding links to duplicate node labels, **only one node is active.  If you try to link to the second one, the link will only be established to the first one.**

Do we want to disallow duplicate labels, or do we want to properly support them as independent nodes?  (This might require a substantial change to the way node ids are handled).

**Comment by benloh** [comment]
@jdanish Any thoughts on duplicate node labels?  Are we wanting to explicitly support duplicate labels?  If we do we might need to do some deep rewrites.  Currently duplicate node labels are broken (e.g. you can only add an edge to one of the duplicates, and not the other).

We currently detect duplicate node names during node Edit and display a warning, but we do not do anything to prevent its creation.  Nor do we scrub newly opened databases for a duplicate node problem.

**Comment by jdanish** [comment]
Kalani says it is common to have duplicate names and disambiguation via other fields so ideally we support that so long as ids are unique.----(from my iPhone)Joshua Danishhttp://www.joshuadanish.comOn Jul 7, 2023, at 1:30 PM, benloh ***@***.***> wrote:﻿
@jdanish Any thoughts on duplicate node labels?  Are we wanting to explicitly support duplicate labels?  If we do we might need to do some deep rewrites.  Currently duplicate node labels are broken (e.g. you can only add an edge to one of the duplicates, and not the other).
We currently detect duplicate node names during node Edit and display a warning, but we do not do anything to prevent its creation.  Nor do we scrub newly opened databases for a duplicate node problem.

**Comment by benloh** [comment]
Fixed with 15fd48e552b3e35f3b2a8483a1abe23b140f59ab
