### ISSUE TITLE
Adapt node / edge tables to allow arbitrary attributes

### ISSUE THREAD

**Issue by jdanish** [netcreateorg/netcreate-itest#45]
For the Spring run, we need the tables to at least show all of the attributes. It's OK if resizing and other things wait until later.

Scrolling to the right might be needed? In which case freezing some of the columns on the left would be nice, but if it is a challenge, ignore.

**Comment by jdanish** [comment]
For the Spring run, we need the tables to at least show all of the attributes. It's OK if resizing and other things wait until later.

Scrolling to the right might be needed? In which case freezing some of the columns on the left would be nice, but if it is a challenge, ignore.

**Comment by jdanish** [comment]
Works for now, but need to revisit with ordering when possible.

**Comment by benloh** [comment]
See also #108

**Comment by benloh** [comment]
This should be implemented already?

**Comment by jdanish** [comment]
Yes except that column sizing doesn’t adapt well.

**Comment by benloh** [comment]
@jdanish it'd be helpful if you could send me screenshots of the kinds of issues you're seeing.  Better yet if you could send me sample database files and templates so I can test live.

**Comment by jdanish** [comment]
OK, here are some samples.

This one is actually pretty OK:
<img width="1210" alt="Screenshot 2024-07-16 at 7 04 21 AM" src="https://github.com/user-attachments/assets/c93fdc9f-681b-4584-aea4-7f7e15b273f2">

These two I wish type were wider: 
<img width="1232" alt="Screenshot 2024-07-16 at 7 03 59 AM" src="https://github.com/user-attachments/assets/4951a233-9bc4-4e62-9b4d-0a6694729bd8">

<img width="1217" alt="Screenshot 2024-07-16 at 7 03 49 AM" src="https://github.com/user-attachments/assets/0cfac1ce-c762-4579-9641-454902946b23">

So ... it's kind of random, it seems?  Not sure what algorithm you are using...  

Attaching the samples which are from: http://159.203.177.172/ (I'll slack the password)

[samples.zip](https://github.com/user-attachments/files/16247673/samples.zip)

**Comment by benloh** [comment]
It's a mix of a few fixed fields and dynamically allocated based on the content.
The ideal solution would use some kind of library/widget that supports resizing, but it might introduce all sorts of other problems.  I'll spend some time with it to see what we can come up with.

**Comment by jdanish** [comment]
Ok, though I’d say the dates, filtering, and putting comments into template are all higher priority, all else being equal.


And yeah … I love the idea of a fully featured table library but 100% agree with the concerns.
