### ISSUE TITLE
Warn or handle duplicate node labels

### ISSUE THREAD

**Issue by jdanish** [netcreateorg/netcreate-itest#56]
Added based on PR https://github.com/netcreateorg/netcreate-itest/pull/39

The ideal functionality is to receive a warning (popup is fine) that allows the user to either continue, or edit the original node. Less ideal is to just have the warning and then they can opt to cancel. 

Edited to add ideal functionality.

**Comment by jdanish** [comment]
Note: if you start to create one then realize you made a mistake, cancel does not delete the duplicate...

**Comment by benloh** [comment]
See also #38

**Comment by benloh** [comment]
TO DO
* [ ] "Duplicate" warning only shows on NCNode, not on NCSearch.
* [ ] Show duplicate warning on NCNode also,  not just AutoComplete?
* [ ] Show ID number in AutoComplete?
* [ ] Show ID number in Edge Source/Target?

**Comment by benloh** [comment]
Implemented with #113
