### ISSUE TITLE
Re-implement MarkDown in notes fields

### ISSUE THREAD

**Issue by jdanish** [netcreateorg/netcreate-itest#58]
Markdown support is no-longer present in string fields. Perhaps this should be a flag in the template so that it is only supported if requested / needed? It was nice for having images and urls in the ItestTeam network as an example. We can definitely limit it to certain fields, though. 

If this does go back in, it'd be nice to also strip out or escape carriage returns that are in markdown when exporting to csv.

**Comment by benloh** [comment]
Joshua writes:
> we wouldn't want to assume kids know markdown, so instead would use a wysiwyg edit for it like this one https://ui.toast.com/tui-editor ... when you look at those tasks can you give us an estimate for the difference between implementing a library like that and just re-integrating the interpreter?  Either way, we'd want to be able to flag which fields can take markdown, but I assume we'd want any that are a "text area" to support it, and any that are just a word / phrase / tag to not bother?

**Comment by jdanish** [comment]
> Notes on Markdown:
> 
> * Sri recommends [markdown-it](https://github.com/markdown-it/markdown-it) as a parser, but it does not support WYSIWYG.

Is that the one we were using before?  If it is a lot easier to integrate, I'd be down with going this direction and then assuming we have a markdown cheatsheet and / or a simple help line added later (lower priority).

**Comment by benloh** [comment]
You had added `markdown-react-js` which has not been updated in 5 years.
You had also added `markdown-it-emoji'.

The toast editor looks a little heavy handed.  So I'm looking for lightweight alternatives.

**Comment by jdanish** [comment]
OK, cool. If it looks unlikely, then markdown-it seems like a good direction to me (from a glance, without looking under the hood, but trusting Sri's read). We can always add some kind of help / support (or printouts) if needed.

**Comment by benloh** [comment]
Implemented with #91
