### ISSUE TITLE
Standalone packaging is now broken and should be fixed

### ISSUE THREAD

**Issue by jdanish** [netcreateorg/netcreate-itest#68]
Running npm run package creates a public folder and html but this no-longer runs on its own. It appears related to the file movement that broke nc-multiplex. 

This can wait until Spring / whenever other infrastructure changes are implemented but I wanted a record.

**Comment by benloh** [comment]
See old wiki for Standalone Mode [instructions](https://github.com/netcreateorg/netcreate-2018/wiki/User-Guide)
See [PR 46](https://github.com/netcreateorg/netcreate-2018/pull/46) for the standalone implementation.

Error when loading `index.html` directly from the browser is:

![screenshot_1509](https://github.com/netcreateorg/netcreate-itest/assets/1403057/399a7a53-c660-43ca-86a3-868b303628cc)

**Comment by benloh** [comment]
Fixed with #177
