### ISSUE TITLE
New nodes default to black instead of the empty node type color

### ISSUE THREAD

**Issue by jdanish** [netcreateorg/netcreate-itest#70]
Setup a template where the color of a node with no type is gray.

Create a new node. The fill color is black.

If you save the node without setting a type, the color remains black.

Change the type to something, then back to blank. The node is now the correct color (gray).

You really should never have this setting on a node, of course, but it does mean any undefined nodes are the wrong color.

**Comment by benloh** [comment]
Fixed with 2542d54a0677c3cece58d4974341980f192342aa
