### ISSUE TITLE
Need to display images in networks

### ISSUE THREAD

**Issue by jdanish** [netcreateorg/netcreate-itest#82]
We have multiple contexts where it is valuable to display an image in the node view (and potentially in edge views). This could be handled in one of two ways (or both):

1. Re-integrate the markdown display.
2. Add a new image attribute type that takes a url for an image from the web.

Note that for for the foreseeable future, the assumption is that these are displayed based on a URL, and we do not need or want to handle storing images.

In either case, one issue to be aware of is that in the prior implementation images were often too big, so needed to be automatically scaled. Ideally, that'd be integrated into the solution.

I'd still like to see markdown supported, but if it is easier to have just an image attribute type short-term, that's plenty for Spring.

**Comment by dsriseah** [comment]
joshua: is this image feature specifically regerring to item 4 in [Net.Create 2.0 Feature Design](https://docs.google.com/document/d/1XpbExyIFNbjC-73Qd1_jQv2D6kAp1gJIj8S95PUX0d8/edit)?

**Comment by jdanish** [comment]
No - this is intended to just literally be a picture on the node like in our team network if we each had a photo on our node that could be viewed in the left panel or when viewing in the table. Note that if we can support images via markdown, I think we can consider skipping the image type at least for now since we'd have a way to embed images (that's what I did previously).

**Comment by dsriseah** [comment]
Ok! If I understand correctly, this is an image hack for purposes of showing the idea to people rather than a template engineering thing  that we have to jump into before we're quite ready for it?

**Comment by dsriseah** [comment]
The old markdown editing did introduce a number of problems that we'd want to solve long-term, so Ben and I are talking through some general approaches to handle the markdown sanitizing + database-related issues and how to build a reusable module for certain kinds of inputs and use cases. Thanks for the clarifications!!!

**Comment by jdanish** [comment]
I am sure you are on it, but it also seemed an issue was trying to render markdown constantly even for nodes that didn't have any, so if we can check that somehow and use a simpler render. Alternatively, if we know a network will be huge, setting a template attribute to make textfields not support markdown might make sense if you don't have a performance solution you are happy with. Apologies if you are way ahead on this :)

**Comment by benloh** [comment]
I believe this shouldn't be too much of an issue if we only render Markdown in the Node Edit and Edge Edit views.  Hover on attributes can also be handled discretely.  The main problem is probably the table views.

**Comment by benloh** [comment]
Issues 

* [ ] Show image in node/edge table
* [ ] Show image in attribute hover

**Comment by benloh** [comment]
Implemented with #91
