### ISSUE TITLE
Delete key press in middle of search term in search bar dumps cursor to end of searched term

### ISSUE THREAD

**Issue by kalanicraig** [netcreateorg/netcreate-itest#87]
Putting the cursor in to the middle of a search term in the upper-left search bar and pressing delete moves the cursor unexpectedly to the end of the search bar.

https://github.com/netcreateorg/netcreate-itest/assets/9748020/c79812ce-52a1-4254-8370-df46826c293c

**Comment by benloh** [comment]
@kalanicraig Thanks for the report.  I think I know what's going on.  How urgent is this fix?

**Comment by benloh** [comment]
Fixed by #92.
