### ISSUE TITLE
Editing a node, then hitting cancel displays the "template being edited" alert.

### ISSUE THREAD

**Issue by jdanish** [netcreateorg/netcreate-itest#88]
To reproduce:

1. Select a node.
2. Click edit.
3. Click cancel.
4. Node should revert to normal. Instead, the red text saying "The template is currently being edited, please try again later." appears and edit is no-longer functioning.
5. Click off and then back, or reload and all is fine.

This is minor since it is easily resolved, but if we can fix it before the Spring run, while in the next round of fixes, that'd be awesome.

**Comment by benloh** [comment]
@jdanish As of 11/17 in the `dev` branch (b7bd9403494d7506a54544b089a5bd0fb336e339) I'm not seeing the bug.  Clicking "Cancel" should release the lock.  Are you able to reproduce this?

I have seen the node get stuck in a locked state while making coding changes, but I haven't found a reproducible action that triggers the bug.

**Comment by jdanish** [comment]
No, I am no-longer seeing it, so I am closing it and assuming you fixed it along the way.
