### ISSUE TITLE
BUG: Filter by Edge Source/Target should use `string` not `number`

### ISSUE THREAD

**Issue by benloh** [netcreateorg/netcreate-itest#94]
Currently the Edge Source and Target filters refer to the source and target `id`s rather than their `labels`.
On the other hand, it does allow filtering by greater than / less than numeric ids.

**Comment by benloh** [comment]
@jdanish I assume that filters for edge source / target would ideally use their string labels rather than numeric ids?

**Comment by jdanish** [comment]
> @jdanish I assume that filters for edge source / target would ideally use their string labels rather than numeric ids?

Yes please!
