### ISSUE TITLE
Node table "view" link acting as "edit"

### ISSUE THREAD

**Issue by jdanish** [netcreateorg/netcreate-itest#96]
In the current build (dev-bl/filter-summary) the view button in the nodes table acts as an edit button. 

Note, if you are logged in, the button on the left of the table reads "edit."  If you are not it reads "view."  The edit button works as intended. The view button also works as an edit button (loads node, and activates edit mode which should not be possible when not logged in). The view button should simply load the specified node and not begin the edit function.

**Comment by benloh** [comment]
Fixed with 4f5e054b86d9f90a9aa4427a176934beae0959d6

**Comment by jdanish** [comment]
Confirmed fixed. Thanks!
